### ISSUE TITLE
(node:9145) UnhandledPromiseRejectionWarning: Error: Request failed with status code 504

### ISSUE THREAD

**Issue by euneuber** [beyondcode/helo-community#16]
Hi, thank you for this very helpful tool! I guess I'm stressing it beyond your imagination...

I'm redirecting postfix from a dev server to my HELO app and it resends literally 1000s of stalled emails... (HELO app does barely respond -- my fault)

But I keep seeing this error:
```
(node:9145) UnhandledPromiseRejectionWarning: Error: Request failed with status code 504
    at e.exports (/tmp/.mount_HELO-1nNcNF3/resources/app.asar/background.js:2:93706)
    at e.exports (/tmp/.mount_HELO-1nNcNF3/resources/app.asar/background.js:2:239741)
    at IncomingMessage.<anonymous> (/tmp/.mount_HELO-1nNcNF3/resources/app.asar/background.js:2:838111)
    at IncomingMessage.emit (events.js:208:15)
    at endReadableNT (_stream_readable.js:1168:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

Is this due to high load or a "real" error?

**Comment by mpociot** [comment]
This should now be fixed in version 1.1.0
